#!/usr/bin/env python3
"""Write a Codex profile for a configured model without storing a key."""

from __future__ import annotations

import argparse
import json
import os
import tempfile
from pathlib import Path


def profile_text(
    model_id: str,
    *,
    provider_id: str,
    daemon_port: int,
    base_url: str | None,
    wire_api: str,
    paid: bool,
) -> str:
    if paid:
        name = provider_id
        endpoint = base_url or ""
        requires_auth = "true"
    else:
        name = "free_model_router"
        endpoint = f"http://127.0.0.1:{daemon_port}/v1"
        requires_auth = "false"
    if not endpoint:
        raise ValueError("a base URL is required for a paid profile")
    return (
        "# Generated by the user-configured free model router.\n"
        "# No credential is stored in this file.\n"
        f"model = {json.dumps(model_id)}\n"
        f"model_provider = {json.dumps(name)}\n\n"
        f"[model_providers.{name}]\n"
        f"name = {json.dumps(name)}\n"
        f"base_url = {json.dumps(endpoint)}\n"
        f"requires_openai_auth = {requires_auth}\n"
        f"wire_api = {json.dumps(wire_api)}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-id", required=True)
    parser.add_argument("--provider-id", required=True)
    parser.add_argument("--daemon-port", type=int, default=4242)
    parser.add_argument("--base-url")
    parser.add_argument("--wire-api", choices=("responses", "chat"), default="responses")
    parser.add_argument("--paid", action="store_true")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if not 1024 <= args.daemon_port <= 65535:
        parser.error("daemon port must be between 1024 and 65535")
    content = profile_text(
        args.model_id,
        provider_id=args.provider_id,
        daemon_port=args.daemon_port,
        base_url=args.base_url,
        wire_api=args.wire_api,
        paid=args.paid,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", dir=args.output.parent, prefix=f".{args.output.name}.", delete=False
    ) as handle:
        handle.write(content)
        temporary = Path(handle.name)
    os.chmod(temporary, 0o600)
    temporary.replace(args.output)
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
